#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"; R="${REPORT_FILE:-tmp/steps-36-40-report.txt}"; mkdir -p "$(dirname "$R")"; : >"$R"; T=0;P=0;F=0
pass() { T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R"; }; fail() { T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R"; }
S() { mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r'; }; DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for x in species varieties processing_methods coffee_grades; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='$x'")" == 1 ]]&&pass "Steps 36-40: table $x"||fail "Steps 36-40: table $x"; done
for x in 'varieties|speciesId|species' 'coffee_beans|speciesId|species' 'coffee_beans|varietyId|varieties'; do IFS='|' read -r t c r<<<"$x"; [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Steps 37-38: $t.$c -> $r"||fail "Steps 37-38: $t.$c -> $r"; done
for c in processingSteps parameters; do [[ "$(S "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='processing_methods' AND COLUMN_NAME='$c'")" == json ]]&&pass "Step 39: $c JSON"||fail "Step 39: $c JSON"; done
for c in minimumCuppingScore maxDefectCount exportEligible isActive sortOrder; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_grades' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 40: coffee_grades.$c"||fail "Step 40: coffee_grades.$c"; done
printf '\nRESULT Steps 36-40: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R"; [[ $F -eq 0 ]]