#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";cd "$ROOT";R="${REPORT_FILE:-tmp/steps-61-65-report.txt}";mkdir -p "$(dirname "$R")";:>"$R";T=0;P=0;F=0
pass(){T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R";};fail(){T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R";};s(){mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r';};DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for c in id uuid coffeeBeanId cuppingScore aroma body acidity sweetness aftertaste description isActive sortOrder;do grep -R -qE "^[[:space:]]*$c[[:space:]]" prisma/schema/sensory-profile.prisma 2>/dev/null&&pass "Step 61: SensoryProfile field $c"||fail "Step 61: SensoryProfile field $c";done
for c in id uuid sensoryProfileId flavorProfileId sortOrder;do grep -R -qE "^[[:space:]]*$c[[:space:]]" prisma/schema/sensory-profile-flavor.prisma 2>/dev/null&&pass "Step 61: SensoryProfileFlavor field $c"||fail "Step 61: SensoryProfileFlavor field $c";done
for op in sensory profile flavor mapping create get list update delete;do grep -R -qi "$op" src/application src/presentation 2>/dev/null&&pass "Step 61: operation $op represented"||fail "Step 61: operation $op missing";done
for pair in 'sensoryProfileId|sensory_profiles' 'flavorProfileId|flavor_profiles';do IFS='|' read -r c r<<<"$pair";[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='sensory_profile_flavors' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Step 61: mapping FK -> $r"||fail "Step 61: mapping FK -> $r";done
for term in coffeeBean regionId farmerId farmId speciesId varietyId processingMethodId gradeId harvestSeasonId sensoryProfile;do grep -R -qi "$term" src/application 2>/dev/null&&pass "Step 62: cross-domain term $term"||fail "Step 62: cross-domain term $term missing";done
for term in page limit offset cursor sort order filter search query;do grep -R -qi "$term" src/application src/presentation 2>/dev/null&&pass "Step 63: query capability $term"||fail "Step 63: query capability $term missing";done
for term in regions farmers farms varieties flavors metadata;do grep -R -qi "$term" src/application src/presentation 2>/dev/null&&pass "Step 64: relationship query $term"||fail "Step 64: relationship query $term missing";done
for term in invalid duplicate active inactive cuppingScore moisture density availableWeight reservedWeight startMonth endMonth farmingSinceYear;do grep -R -qi "$term" src/application src/domain 2>/dev/null&&pass "Step 65: validation/rule term $term"||fail "Step 65: validation/rule term $term missing";done
printf '\nRESULT Steps 61-65: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R";[[ $F -eq 0 ]]