#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"; R="${REPORT_FILE:-tmp/steps-46-50-report.txt}"; mkdir -p "$(dirname "$R")"; : >"$R"; T=0;P=0;F=0
pass() { T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R"; }; fail() { T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R"; }
S() { mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r'; }; DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for x in flavor_profiles sensory_profiles sensory_profile_flavors coffee_beans; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='$x'")" == 1 ]]&&pass "Steps 46-50: table $x"||fail "Steps 46-50: table $x"; done
for x in 'sensory_profile_flavors|sensoryProfileId|sensory_profiles' 'sensory_profile_flavors|flavorProfileId|flavor_profiles' 'sensory_profiles|coffeeBeanId|coffee_beans'; do IFS='|' read -r t c r<<<"$x"; [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Steps 47-48: $t.$c -> $r"||fail "Steps 47-48: $t.$c -> $r"; done
for c in flavorProfiles aromaNotes; do [[ "$(S "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c'")" == json ]]&&pass "Step 49: $c JSON"||fail "Step 49: $c JSON"; done
for c in uuid code category isActive sortOrder; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='flavor_profiles' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 46: flavor_profiles.$c"||fail "Step 46: flavor_profiles.$c"; done
for c in uuid code name regionId speciesId processingMethodId weightUnit isFeatured isActive sortOrder; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 50: coffee_beans.$c"||fail "Step 50: coffee_beans.$c"; done
printf '\nRESULT Steps 46-50: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R"; [[ $F -eq 0 ]]