#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";cd "$ROOT";R="${REPORT_FILE:-tmp/steps-41-45-report.txt}";mkdir -p "$(dirname "$R")";:>"$R";T=0;P=0;F=0
pass(){T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R";};fail(){T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R";};s(){mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r';};DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for x in 'processingMethodId|processing_methods' 'gradeId|coffee_grades';do IFS='|' read -r c r<<<"$x";[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Step 41: CoffeeBean -> $r"||fail "Step 41: CoffeeBean -> $r";done
for c in year seasonType startMonth endMonth isCurrent isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='harvest_seasons' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 42: harvest_seasons.$c"||fail "Step 42: harvest_seasons.$c";done
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='harvest_seasons' AND COLUMN_NAME='year' AND DATA_TYPE='int'")" == 1 ]]&&pass 'Step 42: year integer'||fail 'Step 42: year integer'
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='harvest_seasons' AND COLUMN_NAME='startMonth' AND DATA_TYPE='int'")" == 1 && "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='harvest_seasons' AND COLUMN_NAME='endMonth' AND DATA_TYPE='int'")" == 1 ]]&&pass 'Step 43: month fields integer'||fail 'Step 43: month fields integer'
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='harvestSeasonId' AND REFERENCED_TABLE_NAME='harvest_seasons'")" == 1 ]]&&pass 'Step 43: CoffeeBean -> HarvestSeason'||fail 'Step 43: CoffeeBean -> HarvestSeason'
for c in id uuid code name type issuer website countryScope requiresExpiration description isActive sortOrder createdAt updatedAt;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='certifications' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 44: certifications.$c"||fail "Step 44: certifications.$c";done
for c in uuid code;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='certifications' AND COLUMN_NAME='$c' AND NON_UNIQUE=0")" -ge 1 ]]&&pass "Step 44: certifications.$c unique"||fail "Step 44: certifications.$c unique";done
# Certification has no FK in the database contract. The verifier must protect that boundary rather than inventing one.
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='certifications' AND REFERENCED_TABLE_NAME IS NOT NULL")" == 0 ]]&&pass 'Step 45: Certification has no invented FK'||fail 'Step 45: Certification unexpectedly has FK'
[[ -f docs/master-data-architecture.md || -f docs/database.md || -f README.md ]]&&pass 'Step 45: certification boundary is documentable'||fail 'Step 45: documentation surface missing'
printf '\nRESULT Steps 41-45: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R";[[ $F -eq 0 ]]