#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"
REPORT="${REPORT_FILE:-tmp/steps-31-35-report.txt}"; mkdir -p "$(dirname "$REPORT")"; : > "$REPORT"; T=0;P=0;F=0
pass(){ T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$REPORT";}; fail(){T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$REPORT";}
scalar(){ mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r'; }; DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for x in 'countries|uuid' 'countries|code' 'countries|iso2' 'countries|iso3' 'regions|uuid' 'regions|code'; do IFS='|' read -r t c<<<"$x"; [[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='$c' AND NON_UNIQUE=0")" -ge 1 ]]&&pass "Step 31: unique $t.$c"||fail "Step 31: unique $t.$c";done
for c in name officialName shortName continent timezone phoneCode currency currencyCode isCoffeeOrigin description isActive sortOrder;do [[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='countries' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 31: countries.$c"||fail "Step 31: countries.$c";done
[[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='regions' AND COLUMN_NAME='countryId' AND REFERENCED_TABLE_NAME='countries'")" == 1 ]]&&pass 'Step 31: Country -> Region FK'||fail 'Step 31: Country -> Region FK'
[[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='organizations' AND COLUMN_NAME='regionId' AND REFERENCED_TABLE_NAME='regions'")" == 1 ]]&&pass 'Step 32: Organization -> Region'||fail 'Step 32: Organization -> Region'
for c in type memberCount isActive sortOrder;do [[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='organizations' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 32: organizations.$c"||fail "Step 32: organizations.$c";done
[[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='organizations' AND COLUMN_NAME='code' AND NON_UNIQUE=0")" -ge 1 ]]&&pass 'Step 32: organizations.code unique'||fail 'Step 32: organizations.code unique'
for x in 'regionId|regions' 'organizationId|organizations';do IFS='|' read -r c r<<<"$x"; [[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='farmers' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Step 33: Farmer -> $r"||fail "Step 33: Farmer -> $r";done
for c in contactName phone email farmingSinceYear;do [[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='farmers' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 33: farmers.$c"||fail "Step 33: farmers.$c";done
[[ "$(scalar "SELECT IS_NULLABLE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='farmers' AND COLUMN_NAME='organizationId'")" == YES ]]&&pass 'Step 33: organizationId nullable'||fail 'Step 33: organizationId nullable'
[[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='farms' AND COLUMN_NAME='farmerId' AND REFERENCED_TABLE_NAME='farmers'")" == 1 ]]&&pass 'Step 34: Farm -> Farmer'||fail 'Step 34: Farm -> Farmer'
for c in area areaUnit establishedYear altitudeMin altitudeMax altitudeUnit latitude longitude soilType climate farmingPractice isActive sortOrder;do [[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='farms' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 34: farms.$c"||fail "Step 34: farms.$c";done
[[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='regions' AND COLUMN_NAME='countryId' AND REFERENCED_TABLE_NAME='countries'")" == 1 && "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='farmers' AND COLUMN_NAME='regionId' AND REFERENCED_TABLE_NAME='regions'")" == 1 && "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='farms' AND COLUMN_NAME='farmerId' AND REFERENCED_TABLE_NAME='farmers'")" == 1 ]]&&pass 'Step 35: Country -> Region -> Farmer -> Farm graph'||fail 'Step 35: supply-chain graph'
[[ "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='organizations' AND COLUMN_NAME='regionId' AND REFERENCED_TABLE_NAME='regions'")" == 1 && "$(scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='farmers' AND COLUMN_NAME='organizationId' AND REFERENCED_TABLE_NAME='organizations'")" == 1 ]]&&pass 'Step 35: Region -> Organization -> Farmer graph'||fail 'Step 35: organization graph'
printf '\nRESULT Steps 31-35: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$REPORT";[[ $F -eq 0 ]]