#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";cd "$ROOT";R="${REPORT_FILE:-tmp/steps-36-40-report.txt}";mkdir -p "$(dirname "$R")";:>"$R";T=0;P=0;F=0
pass(){T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R";};fail(){T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R";};s(){mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r';};DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for t in species varieties;do for c in uuid code;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='$c' AND NON_UNIQUE=0")" -ge 1 ]]&&pass "Step 36/37: $t.$c unique"||fail "Step 36/37: $t.$c unique";done;done
for c in name commonName scientificName originRegion isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='species' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 36: species.$c"||fail "Step 36: species.$c";done
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='varieties' AND COLUMN_NAME='speciesId' AND REFERENCED_TABLE_NAME='species'")" == 1 ]]&&pass 'Step 37: Species -> Variety'||fail 'Step 37: Species -> Variety'
for c in geneticBackground originCountry plantCharacteristics flavorCharacteristics description isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='varieties' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 37: varieties.$c"||fail "Step 37: varieties.$c";done
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='speciesId' AND REFERENCED_TABLE_NAME='species'")" == 1 && "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='varietyId' AND REFERENCED_TABLE_NAME='varieties'")" == 1 ]]&&pass 'Step 38: Species/Variety -> CoffeeBean dependencies'||fail 'Step 38: taxonomy dependency graph'
for c in fermentation fermentationType fermentationDuration dryingMethod dryingDuration processingSteps parameters isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='processing_methods' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 39: processing_methods.$c"||fail "Step 39: processing_methods.$c";done
for c in processingSteps parameters;do [[ "$(s "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='processing_methods' AND COLUMN_NAME='$c'")" == json ]]&&pass "Step 39: $c JSON"||fail "Step 39: $c JSON";done
for c in minimumCuppingScore maxDefectCount exportEligible category isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_grades' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 40: coffee_grades.$c"||fail "Step 40: coffee_grades.$c";done
for t in species varieties processing_methods coffee_grades;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='uuid' AND NON_UNIQUE=0")" -ge 1 ]]&&pass "Step 40: $t uuid unique"||fail "Step 40: $t uuid unique";done
printf '\nRESULT Steps 36-40: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R";[[ $F -eq 0 ]]