#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";cd "$ROOT";R="${REPORT_FILE:-tmp/steps-46-50-report.txt}";mkdir -p "$(dirname "$R")";:>"$R";T=0;P=0;F=0
pass(){T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R";};fail(){T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R";};s(){mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r';};DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for c in id uuid code name category description isActive sortOrder createdAt updatedAt;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='flavor_profiles' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 46: flavor_profiles.$c"||fail "Step 46: flavor_profiles.$c";done
for c in uuid code;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='flavor_profiles' AND COLUMN_NAME='$c' AND NON_UNIQUE=0")" -ge 1 ]]&&pass "Step 46: $c unique"||fail "Step 46: $c unique";done
for c in id uuid coffeeBeanId cuppingScore aroma body acidity sweetness aftertaste description isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='sensory_profiles' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 47: sensory_profiles.$c"||fail "Step 47: sensory_profiles.$c";done
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='sensory_profiles' AND COLUMN_NAME='coffeeBeanId' AND NON_UNIQUE=0")" -ge 1 ]]&&pass 'Step 47: one sensory profile per CoffeeBean'||fail 'Step 47: CoffeeBean uniqueness missing'
for x in 'sensoryProfileId|sensory_profiles' 'flavorProfileId|flavor_profiles';do IFS='|' read -r c r<<<"$x";[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='sensory_profile_flavors' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Step 48: mapping -> $r"||fail "Step 48: mapping -> $r";done
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='sensory_profile_flavors' AND COLUMN_NAME='sortOrder' AND DATA_TYPE='int'")" == 1 ]]&&pass 'Step 48: mapping sortOrder'||fail 'Step 48: mapping sortOrder'
for c in flavorProfiles aromaNotes;do [[ "$(s "SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c'")" == json ]]&&pass "Step 49: coffee_beans.$c JSON"||fail "Step 49: coffee_beans.$c JSON";done
[[ -f docs/master-data-architecture.md || -f README.md ]]&&pass 'Step 49: JSON/mapping semantics have documentation surface'||fail 'Step 49: documentation surface missing'
for c in uuid code name regionId farmerId farmId speciesId varietyId processingMethodId gradeId harvestSeasonId cuppingScore moisture density beanSize qualityStatus flavorProfiles aromaNotes availableWeight reservedWeight weightUnit isFeatured isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 50: coffee_beans.$c"||fail "Step 50: coffee_beans.$c";done
printf '\nRESULT Steps 46-50: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R";[[ $F -eq 0 ]]