#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"; cd "$ROOT"; R="${REPORT_FILE:-tmp/steps-41-45-report.txt}"; mkdir -p "$(dirname "$R")"; : >"$R"; T=0;P=0;F=0
pass() { T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R"; }; fail() { T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R"; }
S() { mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r'; }; DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for x in 'coffee_beans|processingMethodId|processing_methods' 'coffee_beans|gradeId|coffee_grades' 'coffee_beans|harvestSeasonId|harvest_seasons'; do IFS='|' read -r t c r<<<"$x"; [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Steps 41-43: $t.$c -> $r"||fail "Steps 41-43: $t.$c -> $r"; done
for c in year seasonType startMonth endMonth isCurrent isActive sortOrder; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='harvest_seasons' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Steps 42-43: harvest_seasons.$c"||fail "Steps 42-43: harvest_seasons.$c"; done
for c in uuid code name issuer countryScope requiresExpiration isActive sortOrder; do [[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='certifications' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 44: certifications.$c"||fail "Step 44: certifications.$c"; done
[[ "$(S "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='certifications' AND REFERENCED_TABLE_NAME IS NOT NULL")" == 0 ]]&&pass 'Step 45: certification has no FK'||fail 'Step 45: certification has unexpected FK'
printf '\nRESULT Steps 41-45: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R"; [[ $F -eq 0 ]]