#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)";cd "$ROOT";R="${REPORT_FILE:-tmp/steps-51-55-report.txt}";mkdir -p "$(dirname "$R")";:>"$R";T=0;P=0;F=0
pass(){T=$((T+1));P=$((P+1));printf 'PASS %s\n' "$*"|tee -a "$R";};fail(){T=$((T+1));F=$((F+1));printf 'FAIL %s\n' "$*"|tee -a "$R";};s(){mysql --protocol=tcp --batch --skip-column-names -h "${DATABASE_HOST:-127.0.0.1}" -P "${DATABASE_PORT:-3306}" -u "${DATABASE_USER:-dev}" -p"${DATABASE_PASSWORD:-dev123}" -e "$1" 2>/dev/null|tail -n1|tr -d '\r';};DB="${DATABASE_NAME:-arunika_coffee_master_data}"
for x in 'regionId|regions' 'farmerId|farmers' 'farmId|farms' 'speciesId|species' 'varietyId|varieties' 'processingMethodId|processing_methods' 'gradeId|coffee_grades' 'harvestSeasonId|harvest_seasons';do IFS='|' read -r c r<<<"$x";[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c' AND REFERENCED_TABLE_NAME='$r'")" == 1 ]]&&pass "Step 51: CoffeeBean -> $r"||fail "Step 51: CoffeeBean -> $r";done
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE CONSTRAINT_SCHEMA='$DB' AND TABLE_NAME='sensory_profiles' AND COLUMN_NAME='coffeeBeanId' AND REFERENCED_TABLE_NAME='coffee_beans'")" == 1 ]]&&pass 'Step 51: CoffeeBean -> SensoryProfile'||fail 'Step 51: CoffeeBean -> SensoryProfile'
for c in cuppingScore moisture density beanSize qualityStatus availableWeight reservedWeight weightUnit isFeatured isActive sortOrder;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 52: coffee_beans.$c"||fail "Step 52: coffee_beans.$c";done
[[ "$(s "SELECT COLUMN_DEFAULT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='weightUnit'")" == kg ]]&&pass 'Step 52: weightUnit default kg'||fail 'Step 52: weightUnit default kg'
[[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='coffee_beans' AND COLUMN_NAME='deletedAt'")" == 0 ]]&&pass 'Step 53: no deletedAt in CoffeeBean contract'||fail 'Step 53: unexpected deletedAt'
for t in countries regions organizations farmers farms species varieties processing_methods coffee_grades harvest_seasons certifications flavor_profiles sensory_profiles coffee_beans;do for c in isActive sortOrder createdAt updatedAt;do [[ "$(s "SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='$DB' AND TABLE_NAME='$t' AND COLUMN_NAME='$c'")" == 1 ]]&&pass "Step 53: $t.$c"||fail "Step 53: $t.$c";done;done
[[ -d prisma/schema && -f prisma.config.ts ]]&&pass 'Step 54: Prisma schema composition exists'||fail 'Step 54: Prisma schema composition missing'
grep -R -q '@relation' prisma/schema 2>/dev/null&&pass 'Step 54: Prisma relation definitions exist'||fail 'Step 54: Prisma relations missing'
grep -R -q 'PrismaClient' src 2>/dev/null&&pass 'Step 55: Prisma Client is wired'||fail 'Step 55: Prisma Client wiring missing'
grep -R -qE 'repository|Repository' src/application src/domain src/infrastructure 2>/dev/null&&pass 'Step 55: repository abstraction present'||fail 'Step 55: repository abstraction missing'
printf '\nRESULT Steps 51-55: %s PASS / %s FAIL\n' "$P" "$F"|tee -a "$R";[[ $F -eq 0 ]]