import type { Prisma } from '../generated/prisma/client.js';

export async function seedCoffeeBean(
  tx: Prisma.TransactionClient,
  regionId: string,
  farmerId: string,
  farmId: string,
  speciesId: string,
  varietyId: string,
  processingMethodId: string,
  gradeId: string,
  harvestSeasonId: string,
) {
  return tx.coffeeBean.upsert({
    where: { code: 'ARUNIKA-SEED-001' },
    update: {
      regionId,
      farmerId,
      farmId,
      speciesId,
      varietyId,
      processingMethodId,
      gradeId,
      harvestSeasonId,
      name: 'Arunika Seed Lot',
      isActive: true,
      sortOrder: 1,
    },
    create: {
      uuid: '00000000-0000-4000-8000-000000000013',
      code: 'ARUNIKA-SEED-001',
      lotNumber: 'SEED-2026-001',
      name: 'Arunika Seed Lot',
      regionId,
      farmerId,
      farmId,
      speciesId,
      varietyId,
      processingMethodId,
      gradeId,
      harvestSeasonId,
      cuppingScore: 84.5,
      moisture: 11.2,
      density: 0.72,
      beanSize: 'screen-16',
      qualityStatus: 'approved',
      flavorProfiles: ['chocolate'],
      aromaNotes: ['cocoa', 'caramel'],
      availableWeight: 100,
      reservedWeight: 10,
      weightUnit: 'kg',
      isFeatured: true,
      isActive: true,
      sortOrder: 1,
    },
  });
}
